version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: usermanagement-postgres
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: